node{

stage("git clone"){   
 checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/hardeepsinghbamrah/askay.git']]])


}


stage("test"){
 echo "testing"	

}

stage("running k8s yaml"){
 sh "kubectl apply -f elasticsearch/svc.yaml"	
 sh "kubectl apply -f elasticsearch/els.yaml"	
}

	
}
