node{

stage("git clone"){   
 checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/hardeepsinghbamrah/askay.git']]])
	
}
	
}
